[project]
name = "greatlearning-31734"
version = "0.1.0"
requires-python = ">=3.13.5,<3.14"
dependencies = [
    "numpy",
    "matplotlib",
    "scipy",
    "tensorflow[and-cuda]",
]

[dependency-groups]
dev = [
    "ruff",
]

[tool.ruff]
src = ["exercises"]

[tool.ruff.format]
